### PR TITLE
[Fix] warning: circular argument reference no_response_wrapper Use ruby2.2.0

### PR DESCRIPTION
**Pull request by 0tofu**

### CODE REVIEW

**Comment by romainbutteaud** [comment]
:+1:

**Comment by joshuaNathaniel** [comment]
:+1:

**Comment by jbolles5** [comment]
+1

**Comment by johalf** [comment]
:+1:

**Comment by zhu1230** [comment]
+1

**Comment by dhartoto** [comment]
+1

**Comment by holinnn** [comment]
:+1:

**Comment by goddamnyouryan** [comment]
:+1:

**Comment by squanto** [comment]
:+1:

**Comment by jelmersnoeck** [comment]
:+1:

**Comment by antoniobg** [comment]
:thumbsup:

**Comment by AndrewHYi** [comment]
:thumbsup:

**Comment by justinstern** [comment]
:+1:

**Comment by klacointe** [comment]
PR wIth some other fixes for ruby 2.2.0: https://github.com/Instagram/instagram-ruby-gem/pull/150

**Comment by ivan-kolmychek** [comment]
(y)

**Comment by toao** [comment]
:+1:

**Comment by albertobissacco** [comment]
:+1:

**Comment by alexbaldwin** [comment]
:+1:

**Comment by gregnar** [comment]
:+1:

**Comment by iagopiimenta** [comment]
:+1:

**Comment by MaxSchmeling** [comment]
:+1:

**Comment by Intrepidd** [comment]
:+1:

**Pull request merged**
