### PR TITLE
Ruby2.2.0 compatibility

### PR DESCRIPTION
**Pull request by klacointe**
Few fixes for ruby 2.2.0 compatibility

### CODE REVIEW

**Comment by antonzaytsev** [comment]
+1 need these changes too.

**Comment by such** [comment]
:+1:

**Comment by ivan-kolmychek** [comment]
this pull-request is almost a month old and stil is not accepted - why?

**Comment by toao** [comment]
project collaborators, Y U NO merge?

**Comment by mcgoooo** [comment]
Yeah would be nice to get this merged please

**Comment by jelmersnoeck** [comment]
:+1:

**Comment by iagopiimenta** [comment]
:+1:

**Comment by jbolles5** [comment]
Please merge this. Incredibly annoying that it has taken this long.

**Comment by klacointe** [comment]
Thanks

**Comment by mcgoooo** [comment]
please merge, really annoying

**Pull request merged**
